-- =============================================================================
-- Cloudberry Performance Test - Data Loading
-- =============================================================================
-- Load CSV data generated by generate-dataset.sh.
-- Adjust the file paths if running from a different directory.

-- Load customers
\echo 'Loading customers...'
COPY customers (id, first_name, last_name, email, city, state, country, created_at)
FROM '/var/loadtest/data/customers.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');

-- Load orders
\echo 'Loading orders...'
COPY orders (id, customer_id, product_id, quantity, price, order_date, status, notes)
FROM '/var/loadtest/data/orders.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');

-- Refresh statistics after loading.
\echo 'Analyzing tables...'
ANALYZE customers;
ANALYZE orders;

\echo 'Data loading complete.'
