//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudberryCluster) DeepCopyInto(out *CloudberryCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudberryCluster.
func (in *CloudberryCluster) DeepCopy() *CloudberryCluster {
	if in == nil {
		return nil
	}
	out := new(CloudberryCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudberryCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudberryClusterList) DeepCopyInto(out *CloudberryClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudberryCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudberryClusterList.
func (in *CloudberryClusterList) DeepCopy() *CloudberryClusterList {
	if in == nil {
		return nil
	}
	out := new(CloudberryClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudberryClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CloudberryClusterSpec) DeepCopyInto(out *CloudberryClusterSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]ImagePullSecret, len(*in))
		copy(*out, *in)
	}
	in.Coordinator.DeepCopyInto(&out.Coordinator)
	if in.Standby != nil {
		in, out := &in.Standby, &out.Standby
		*out = new(StandbySpec)
		(*in).DeepCopyInto(*out)
	}
	in.Segments.DeepCopyInto(&out.Segments)
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HA != nil {
		in, out := &in.HA, &out.HA
		*out = new(HASpec)
		**out = **in
	}
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(VaultSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		**out = **in
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		**out = **in
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryMonitoring != nil {
		in, out := &in.QueryMonitoring, &out.QueryMonitoring
		*out = new(QueryMonitoringSpec)
		**out = **in
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DataLoading != nil {
		in, out := &in.DataLoading, &out.DataLoading
		*out = new(DataLoadingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CloudberryClusterSpec) DeepCopy() *CloudberryClusterSpec {
	if in == nil {
		return nil
	}
	out := new(CloudberryClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CloudberryClusterStatus) DeepCopyInto(out *CloudberryClusterStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.LastConfigChangeTime != nil {
		in, out := &in.LastConfigChangeTime, &out.LastConfigChangeTime
		*out = (*in).DeepCopy()
	}
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailedSegments != nil {
		in, out := &in.FailedSegments, &out.FailedSegments
		*out = make([]FailedSegment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CloudberryClusterStatus) DeepCopy() *CloudberryClusterStatus {
	if in == nil {
		return nil
	}
	out := new(CloudberryClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CoordinatorSpec) DeepCopyInto(out *CoordinatorSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	out.Storage = in.Storage
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CoordinatorSpec) DeepCopy() *CoordinatorSpec {
	if in == nil {
		return nil
	}
	out := new(CoordinatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *StandbySpec) DeepCopyInto(out *StandbySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *StandbySpec) DeepCopy() *StandbySpec {
	if in == nil {
		return nil
	}
	out := new(StandbySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SegmentsSpec) DeepCopyInto(out *SegmentsSpec) {
	*out = *in
	if in.Mirroring != nil {
		in, out := &in.Mirroring, &out.Mirroring
		*out = new(MirroringSpec)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	out.Storage = in.Storage
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SegmentsSpec) DeepCopy() *SegmentsSpec {
	if in == nil {
		return nil
	}
	out := new(SegmentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *MirroringSpec) DeepCopyInto(out *MirroringSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *MirroringSpec) DeepCopy() *MirroringSpec {
	if in == nil {
		return nil
	}
	out := new(MirroringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(BasicAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HBARules != nil {
		in, out := &in.HBARules, &out.HBARules
		*out = make([]HBARule, len(*in))
		copy(*out, *in)
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(SSLSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *BasicAuthSpec) DeepCopyInto(out *BasicAuthSpec) {
	*out = *in
	if in.AdminPasswordSecret != nil {
		in, out := &in.AdminPasswordSecret, &out.AdminPasswordSecret
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *BasicAuthSpec) DeepCopy() *BasicAuthSpec {
	if in == nil {
		return nil
	}
	out := new(BasicAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *OIDCSpec) DeepCopyInto(out *OIDCSpec) {
	*out = *in
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(OIDCSecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RoleMapping != nil {
		in, out := &in.RoleMapping, &out.RoleMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *OIDCSpec) DeepCopy() *OIDCSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *OIDCSecretRef) DeepCopyInto(out *OIDCSecretRef) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *OIDCSecretRef) DeepCopy() *OIDCSecretRef {
	if in == nil {
		return nil
	}
	out := new(OIDCSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *HBARule) DeepCopyInto(out *HBARule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *HBARule) DeepCopy() *HBARule {
	if in == nil {
		return nil
	}
	out := new(HBARule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SSLSpec) DeepCopyInto(out *SSLSpec) {
	*out = *in
	if in.CertSecret != nil {
		in, out := &in.CertSecret, &out.CertSecret
		*out = new(CertSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SSLSpec) DeepCopy() *SSLSpec {
	if in == nil {
		return nil
	}
	out := new(SSLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CertSecretRef) DeepCopyInto(out *CertSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CertSecretRef) DeepCopy() *CertSecretRef {
	if in == nil {
		return nil
	}
	out := new(CertSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ConfigSpec) DeepCopyInto(out *ConfigSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CoordinatorParameters != nil {
		in, out := &in.CoordinatorParameters, &out.CoordinatorParameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DatabaseParameters != nil {
		in, out := &in.DatabaseParameters, &out.DatabaseParameters
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			innerMap := make(map[string]string, len(val))
			for k, v := range val {
				innerMap[k] = v
			}
			(*out)[key] = innerMap
		}
	}
	if in.RoleParameters != nil {
		in, out := &in.RoleParameters, &out.RoleParameters
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			innerMap := make(map[string]string, len(val))
			for k, v := range val {
				innerMap[k] = v
			}
			(*out)[key] = innerMap
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ConfigSpec) DeepCopy() *ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *HASpec) DeepCopyInto(out *HASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *HASpec) DeepCopy() *HASpec {
	if in == nil {
		return nil
	}
	out := new(HASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VaultSpec) DeepCopyInto(out *VaultSpec) {
	*out = *in
	if in.TLSSecret != nil {
		in, out := &in.TLSSecret, &out.TLSSecret
		*out = new(VaultTLSSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *VaultSpec) DeepCopy() *VaultSpec {
	if in == nil {
		return nil
	}
	out := new(VaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VaultTLSSecret) DeepCopyInto(out *VaultTLSSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *VaultTLSSecret) DeepCopy() *VaultTLSSecret {
	if in == nil {
		return nil
	}
	out := new(VaultTLSSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(ResourceList)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ResourceList)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ResourceList) DeepCopyInto(out *ResourceList) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ResourceList) DeepCopy() *ResourceList {
	if in == nil {
		return nil
	}
	out := new(ResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *Toleration) DeepCopyInto(out *Toleration) {
	*out = *in
	if in.TolerationSeconds != nil {
		in, out := &in.TolerationSeconds, &out.TolerationSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *Toleration) DeepCopy() *Toleration {
	if in == nil {
		return nil
	}
	out := new(Toleration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *FailedSegment) DeepCopyInto(out *FailedSegment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *FailedSegment) DeepCopy() *FailedSegment {
	if in == nil {
		return nil
	}
	out := new(FailedSegment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ImagePullSecret) DeepCopyInto(out *ImagePullSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ImagePullSecret) DeepCopy() *ImagePullSecret {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	if in.ResourceGroups != nil {
		in, out := &in.ResourceGroups, &out.ResourceGroups
		*out = make([]ResourceGroupSpec, len(*in))
		copy(*out, *in)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]WorkloadRule, len(*in))
		copy(*out, *in)
	}
	if in.IdleRules != nil {
		in, out := &in.IdleRules, &out.IdleRules
		*out = make([]IdleSessionRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ResourceGroupSpec) DeepCopyInto(out *ResourceGroupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ResourceGroupSpec) DeepCopy() *ResourceGroupSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *WorkloadRule) DeepCopyInto(out *WorkloadRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *WorkloadRule) DeepCopy() *WorkloadRule {
	if in == nil {
		return nil
	}
	out := new(WorkloadRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *IdleSessionRule) DeepCopyInto(out *IdleSessionRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *IdleSessionRule) DeepCopy() *IdleSessionRule {
	if in == nil {
		return nil
	}
	out := new(IdleSessionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *QueryMonitoringSpec) DeepCopyInto(out *QueryMonitoringSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *QueryMonitoringSpec) DeepCopy() *QueryMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(QueryMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
	out.Retention = in.Retention
	in.Destination.DeepCopyInto(&out.Destination)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *BackupRetention) DeepCopyInto(out *BackupRetention) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *BackupRetention) DeepCopy() *BackupRetention {
	if in == nil {
		return nil
	}
	out := new(BackupRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *BackupDestination) DeepCopyInto(out *BackupDestination) {
	*out = *in
	if in.CredentialSecret != nil {
		in, out := &in.CredentialSecret, &out.CredentialSecret
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *BackupDestination) DeepCopy() *BackupDestination {
	if in == nil {
		return nil
	}
	out := new(BackupDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DataLoadingSpec) DeepCopyInto(out *DataLoadingSpec) {
	*out = *in
	if in.StreamingServer != nil {
		in, out := &in.StreamingServer, &out.StreamingServer
		*out = new(StreamingServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]DataLoadingJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DataLoadingSpec) DeepCopy() *DataLoadingSpec {
	if in == nil {
		return nil
	}
	out := new(DataLoadingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *StreamingServerSpec) DeepCopyInto(out *StreamingServerSpec) {
	*out = *in
	if in.CredentialSecret != nil {
		in, out := &in.CredentialSecret, &out.CredentialSecret
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *StreamingServerSpec) DeepCopy() *StreamingServerSpec {
	if in == nil {
		return nil
	}
	out := new(StreamingServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DataLoadingJob) DeepCopyInto(out *DataLoadingJob) {
	*out = *in
	if in.S3Source != nil {
		in, out := &in.S3Source, &out.S3Source
		*out = new(S3SourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KafkaSource != nil {
		in, out := &in.KafkaSource, &out.KafkaSource
		*out = new(KafkaSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RabbitMQSource != nil {
		in, out := &in.RabbitMQSource, &out.RabbitMQSource
		*out = new(RabbitMQSourceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DataLoadingJob) DeepCopy() *DataLoadingJob {
	if in == nil {
		return nil
	}
	out := new(DataLoadingJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *S3SourceSpec) DeepCopyInto(out *S3SourceSpec) {
	*out = *in
	if in.CredentialSecret != nil {
		in, out := &in.CredentialSecret, &out.CredentialSecret
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *S3SourceSpec) DeepCopy() *S3SourceSpec {
	if in == nil {
		return nil
	}
	out := new(S3SourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *KafkaSourceSpec) DeepCopyInto(out *KafkaSourceSpec) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *KafkaSourceSpec) DeepCopy() *KafkaSourceSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *RabbitMQSourceSpec) DeepCopyInto(out *RabbitMQSourceSpec) {
	*out = *in
	if in.CredentialSecret != nil {
		in, out := &in.CredentialSecret, &out.CredentialSecret
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *RabbitMQSourceSpec) DeepCopy() *RabbitMQSourceSpec {
	if in == nil {
		return nil
	}
	out := new(RabbitMQSourceSpec)
	in.DeepCopyInto(out)
	return out
}
