//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(BasicAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HBARules != nil {
		in, out := &in.HBARules, &out.HBARules
		*out = make([]HBARule, len(*in))
		copy(*out, *in)
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(SSLSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupDestination) DeepCopyInto(out *BackupDestination) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Destination)
		(*in).DeepCopyInto(*out)
	}
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalDestination)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupDestination.
func (in *BackupDestination) DeepCopy() *BackupDestination {
	if in == nil {
		return nil
	}
	out := new(BackupDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupHistoryEntry) DeepCopyInto(out *BackupHistoryEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupHistoryEntry.
func (in *BackupHistoryEntry) DeepCopy() *BackupHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(BackupHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupJobTemplate) DeepCopyInto(out *BackupJobTemplate) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]ImagePullSecret, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupJobTemplate.
func (in *BackupJobTemplate) DeepCopy() *BackupJobTemplate {
	if in == nil {
		return nil
	}
	out := new(BackupJobTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRetention) DeepCopyInto(out *BackupRetention) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRetention.
func (in *BackupRetention) DeepCopy() *BackupRetention {
	if in == nil {
		return nil
	}
	out := new(BackupRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
	out.Retention = in.Retention
	in.Destination.DeepCopyInto(&out.Destination)
	if in.Gpbackup != nil {
		in, out := &in.Gpbackup, &out.Gpbackup
		*out = new(GpbackupOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Gprestore != nil {
		in, out := &in.Gprestore, &out.Gprestore
		*out = new(GprestoreOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.JobTemplate != nil {
		in, out := &in.JobTemplate, &out.JobTemplate
		*out = new(BackupJobTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.Validation != nil {
		in, out := &in.Validation, &out.Validation
		*out = new(BackupValidation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSpec.
func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupValidation) DeepCopyInto(out *BackupValidation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupValidation.
func (in *BackupValidation) DeepCopy() *BackupValidation {
	if in == nil {
		return nil
	}
	out := new(BackupValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthSpec) DeepCopyInto(out *BasicAuthSpec) {
	*out = *in
	if in.AdminPasswordSecret != nil {
		in, out := &in.AdminPasswordSecret, &out.AdminPasswordSecret
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthSpec.
func (in *BasicAuthSpec) DeepCopy() *BasicAuthSpec {
	if in == nil {
		return nil
	}
	out := new(BasicAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertSecretRef) DeepCopyInto(out *CertSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertSecretRef.
func (in *CertSecretRef) DeepCopy() *CertSecretRef {
	if in == nil {
		return nil
	}
	out := new(CertSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudberryCluster) DeepCopyInto(out *CloudberryCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudberryCluster.
func (in *CloudberryCluster) DeepCopy() *CloudberryCluster {
	if in == nil {
		return nil
	}
	out := new(CloudberryCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudberryCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudberryClusterList) DeepCopyInto(out *CloudberryClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudberryCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudberryClusterList.
func (in *CloudberryClusterList) DeepCopy() *CloudberryClusterList {
	if in == nil {
		return nil
	}
	out := new(CloudberryClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudberryClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudberryClusterSpec) DeepCopyInto(out *CloudberryClusterSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]ImagePullSecret, len(*in))
		copy(*out, *in)
	}
	in.Coordinator.DeepCopyInto(&out.Coordinator)
	if in.Standby != nil {
		in, out := &in.Standby, &out.Standby
		*out = new(StandbySpec)
		(*in).DeepCopyInto(*out)
	}
	in.Segments.DeepCopyInto(&out.Segments)
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HA != nil {
		in, out := &in.HA, &out.HA
		*out = new(HASpec)
		**out = **in
	}
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(VaultSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		**out = **in
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		**out = **in
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryMonitoring != nil {
		in, out := &in.QueryMonitoring, &out.QueryMonitoring
		*out = new(QueryMonitoringSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DataLoading != nil {
		in, out := &in.DataLoading, &out.DataLoading
		*out = new(DataLoadingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageManagementSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudberryClusterSpec.
func (in *CloudberryClusterSpec) DeepCopy() *CloudberryClusterSpec {
	if in == nil {
		return nil
	}
	out := new(CloudberryClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudberryClusterStatus) DeepCopyInto(out *CloudberryClusterStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.LastConfigChangeTime != nil {
		in, out := &in.LastConfigChangeTime, &out.LastConfigChangeTime
		*out = (*in).DeepCopy()
	}
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.BackupHistory != nil {
		in, out := &in.BackupHistory, &out.BackupHistory
		*out = make([]BackupHistoryEntry, len(*in))
		copy(*out, *in)
	}
	if in.DataLoading != nil {
		in, out := &in.DataLoading, &out.DataLoading
		*out = new(DataLoadingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailedSegments != nil {
		in, out := &in.FailedSegments, &out.FailedSegments
		*out = make([]FailedSegment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudberryClusterStatus.
func (in *CloudberryClusterStatus) DeepCopy() *CloudberryClusterStatus {
	if in == nil {
		return nil
	}
	out := new(CloudberryClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSpec) DeepCopyInto(out *ConfigSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CoordinatorParameters != nil {
		in, out := &in.CoordinatorParameters, &out.CoordinatorParameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DatabaseParameters != nil {
		in, out := &in.DatabaseParameters, &out.DatabaseParameters
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.RoleParameters != nil {
		in, out := &in.RoleParameters, &out.RoleParameters
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSpec.
func (in *ConfigSpec) DeepCopy() *ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoordinatorSpec) DeepCopyInto(out *CoordinatorSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	out.Storage = in.Storage
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoordinatorSpec.
func (in *CoordinatorSpec) DeepCopy() *CoordinatorSpec {
	if in == nil {
		return nil
	}
	out := new(CoordinatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadHealthChecksSpec) DeepCopyInto(out *DataLoadHealthChecksSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadHealthChecksSpec.
func (in *DataLoadHealthChecksSpec) DeepCopy() *DataLoadHealthChecksSpec {
	if in == nil {
		return nil
	}
	out := new(DataLoadHealthChecksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadingJob) DeepCopyInto(out *DataLoadingJob) {
	*out = *in
	if in.PxfJob != nil {
		in, out := &in.PxfJob, &out.PxfJob
		*out = new(PxfJobSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GploadJob != nil {
		in, out := &in.GploadJob, &out.GploadJob
		*out = new(GploadJobSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadingJob.
func (in *DataLoadingJob) DeepCopy() *DataLoadingJob {
	if in == nil {
		return nil
	}
	out := new(DataLoadingJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadingJobStatus) DeepCopyInto(out *DataLoadingJobStatus) {
	*out = *in
	if in.LastRun != nil {
		in, out := &in.LastRun, &out.LastRun
		*out = (*in).DeepCopy()
	}
	if in.RowsLoaded != nil {
		in, out := &in.RowsLoaded, &out.RowsLoaded
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadingJobStatus.
func (in *DataLoadingJobStatus) DeepCopy() *DataLoadingJobStatus {
	if in == nil {
		return nil
	}
	out := new(DataLoadingJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadingJobTemplate) DeepCopyInto(out *DataLoadingJobTemplate) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadingJobTemplate.
func (in *DataLoadingJobTemplate) DeepCopy() *DataLoadingJobTemplate {
	if in == nil {
		return nil
	}
	out := new(DataLoadingJobTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadingPxfStatus) DeepCopyInto(out *DataLoadingPxfStatus) {
	*out = *in
	if in.ExtensionsInstalled != nil {
		in, out := &in.ExtensionsInstalled, &out.ExtensionsInstalled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadingPxfStatus.
func (in *DataLoadingPxfStatus) DeepCopy() *DataLoadingPxfStatus {
	if in == nil {
		return nil
	}
	out := new(DataLoadingPxfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadingSpec) DeepCopyInto(out *DataLoadingSpec) {
	*out = *in
	if in.Pxf != nil {
		in, out := &in.Pxf, &out.Pxf
		*out = new(PxfSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gpfdist != nil {
		in, out := &in.Gpfdist, &out.Gpfdist
		*out = new(GpfdistSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]DataLoadingJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.JobTemplate != nil {
		in, out := &in.JobTemplate, &out.JobTemplate
		*out = new(DataLoadingJobTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthChecks != nil {
		in, out := &in.HealthChecks, &out.HealthChecks
		*out = new(DataLoadHealthChecksSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadingSpec.
func (in *DataLoadingSpec) DeepCopy() *DataLoadingSpec {
	if in == nil {
		return nil
	}
	out := new(DataLoadingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadingStatus) DeepCopyInto(out *DataLoadingStatus) {
	*out = *in
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]DataLoadingJobStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pxf != nil {
		in, out := &in.Pxf, &out.Pxf
		*out = new(DataLoadingPxfStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadingStatus.
func (in *DataLoadingStatus) DeepCopy() *DataLoadingStatus {
	if in == nil {
		return nil
	}
	out := new(DataLoadingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorHandlingSpec) DeepCopyInto(out *ErrorHandlingSpec) {
	*out = *in
	if in.LogErrors != nil {
		in, out := &in.LogErrors, &out.LogErrors
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorHandlingSpec.
func (in *ErrorHandlingSpec) DeepCopy() *ErrorHandlingSpec {
	if in == nil {
		return nil
	}
	out := new(ErrorHandlingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExporterSpec) DeepCopyInto(out *ExporterSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExporterSpec.
func (in *ExporterSpec) DeepCopy() *ExporterSpec {
	if in == nil {
		return nil
	}
	out := new(ExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedSegment) DeepCopyInto(out *FailedSegment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedSegment.
func (in *FailedSegment) DeepCopy() *FailedSegment {
	if in == nil {
		return nil
	}
	out := new(FailedSegment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpbackupOptions) DeepCopyInto(out *GpbackupOptions) {
	*out = *in
	if in.WithStats != nil {
		in, out := &in.WithStats, &out.WithStats
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpbackupOptions.
func (in *GpbackupOptions) DeepCopy() *GpbackupOptions {
	if in == nil {
		return nil
	}
	out := new(GpbackupOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpfdistSpec) DeepCopyInto(out *GpfdistSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpfdistSpec.
func (in *GpfdistSpec) DeepCopy() *GpfdistSpec {
	if in == nil {
		return nil
	}
	out := new(GpfdistSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GploadInputSourceSpec) DeepCopyInto(out *GploadInputSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GploadInputSourceSpec.
func (in *GploadInputSourceSpec) DeepCopy() *GploadInputSourceSpec {
	if in == nil {
		return nil
	}
	out := new(GploadInputSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GploadJobSpec) DeepCopyInto(out *GploadJobSpec) {
	*out = *in
	if in.InputSource != nil {
		in, out := &in.InputSource, &out.InputSource
		*out = new(GploadInputSourceSpec)
		**out = **in
	}
	if in.FilePaths != nil {
		in, out := &in.FilePaths, &out.FilePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(bool)
		**out = **in
	}
	if in.MatchColumns != nil {
		in, out := &in.MatchColumns, &out.MatchColumns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UpdateColumns != nil {
		in, out := &in.UpdateColumns, &out.UpdateColumns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Preload != nil {
		in, out := &in.Preload, &out.Preload
		*out = new(GploadPreloadSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostActions != nil {
		in, out := &in.PostActions, &out.PostActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ErrorHandling != nil {
		in, out := &in.ErrorHandling, &out.ErrorHandling
		*out = new(ErrorHandlingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GploadJobSpec.
func (in *GploadJobSpec) DeepCopy() *GploadJobSpec {
	if in == nil {
		return nil
	}
	out := new(GploadJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GploadPreloadSpec) DeepCopyInto(out *GploadPreloadSpec) {
	*out = *in
	if in.Truncate != nil {
		in, out := &in.Truncate, &out.Truncate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GploadPreloadSpec.
func (in *GploadPreloadSpec) DeepCopy() *GploadPreloadSpec {
	if in == nil {
		return nil
	}
	out := new(GploadPreloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GprestoreOptions) DeepCopyInto(out *GprestoreOptions) {
	*out = *in
	if in.WithStats != nil {
		in, out := &in.WithStats, &out.WithStats
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GprestoreOptions.
func (in *GprestoreOptions) DeepCopy() *GprestoreOptions {
	if in == nil {
		return nil
	}
	out := new(GprestoreOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HASpec) DeepCopyInto(out *HASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HASpec.
func (in *HASpec) DeepCopy() *HASpec {
	if in == nil {
		return nil
	}
	out := new(HASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HBARule) DeepCopyInto(out *HBARule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HBARule.
func (in *HBARule) DeepCopy() *HBARule {
	if in == nil {
		return nil
	}
	out := new(HBARule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleSessionRule) DeepCopyInto(out *IdleSessionRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleSessionRule.
func (in *IdleSessionRule) DeepCopy() *IdleSessionRule {
	if in == nil {
		return nil
	}
	out := new(IdleSessionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecret) DeepCopyInto(out *ImagePullSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecret.
func (in *ImagePullSecret) DeepCopy() *ImagePullSecret {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalDestination) DeepCopyInto(out *LocalDestination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalDestination.
func (in *LocalDestination) DeepCopy() *LocalDestination {
	if in == nil {
		return nil
	}
	out := new(LocalDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirroringSpec) DeepCopyInto(out *MirroringSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirroringSpec.
func (in *MirroringSpec) DeepCopy() *MirroringSpec {
	if in == nil {
		return nil
	}
	out := new(MirroringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCSecretRef) DeepCopyInto(out *OIDCSecretRef) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCSecretRef.
func (in *OIDCSecretRef) DeepCopy() *OIDCSecretRef {
	if in == nil {
		return nil
	}
	out := new(OIDCSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCSpec) DeepCopyInto(out *OIDCSpec) {
	*out = *in
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(OIDCSecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RoleMapping != nil {
		in, out := &in.RoleMapping, &out.RoleMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCSpec.
func (in *OIDCSpec) DeepCopy() *OIDCSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitioningSpec) DeepCopyInto(out *PartitioningSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitioningSpec.
func (in *PartitioningSpec) DeepCopy() *PartitioningSpec {
	if in == nil {
		return nil
	}
	out := new(PartitioningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PxfCustomConnector) DeepCopyInto(out *PxfCustomConnector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PxfCustomConnector.
func (in *PxfCustomConnector) DeepCopy() *PxfCustomConnector {
	if in == nil {
		return nil
	}
	out := new(PxfCustomConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PxfExtensionsSpec) DeepCopyInto(out *PxfExtensionsSpec) {
	*out = *in
	if in.Pxf != nil {
		in, out := &in.Pxf, &out.Pxf
		*out = new(bool)
		**out = **in
	}
	if in.PxfFdw != nil {
		in, out := &in.PxfFdw, &out.PxfFdw
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PxfExtensionsSpec.
func (in *PxfExtensionsSpec) DeepCopy() *PxfExtensionsSpec {
	if in == nil {
		return nil
	}
	out := new(PxfExtensionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PxfJobSpec) DeepCopyInto(out *PxfJobSpec) {
	*out = *in
	if in.FilterPushdown != nil {
		in, out := &in.FilterPushdown, &out.FilterPushdown
		*out = new(bool)
		**out = **in
	}
	if in.ColumnProjection != nil {
		in, out := &in.ColumnProjection, &out.ColumnProjection
		*out = new(bool)
		**out = **in
	}
	if in.Partitioning != nil {
		in, out := &in.Partitioning, &out.Partitioning
		*out = new(PartitioningSpec)
		**out = **in
	}
	if in.ErrorHandling != nil {
		in, out := &in.ErrorHandling, &out.ErrorHandling
		*out = new(ErrorHandlingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Continuous != nil {
		in, out := &in.Continuous, &out.Continuous
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PxfJobSpec.
func (in *PxfJobSpec) DeepCopy() *PxfJobSpec {
	if in == nil {
		return nil
	}
	out := new(PxfJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PxfKerberosSpec) DeepCopyInto(out *PxfKerberosSpec) {
	*out = *in
	out.KeytabSecret = in.KeytabSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PxfKerberosSpec.
func (in *PxfKerberosSpec) DeepCopy() *PxfKerberosSpec {
	if in == nil {
		return nil
	}
	out := new(PxfKerberosSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PxfServerSpec) DeepCopyInto(out *PxfServerSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hive != nil {
		in, out := &in.Hive, &out.Hive
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hbase != nil {
		in, out := &in.Hbase, &out.Hbase
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Jdbc != nil {
		in, out := &in.Jdbc, &out.Jdbc
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CredentialSecrets != nil {
		in, out := &in.CredentialSecrets, &out.CredentialSecrets
		*out = make([]SecretReference, len(*in))
		copy(*out, *in)
	}
	if in.Kerberos != nil {
		in, out := &in.Kerberos, &out.Kerberos
		*out = new(PxfKerberosSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PxfServerSpec.
func (in *PxfServerSpec) DeepCopy() *PxfServerSpec {
	if in == nil {
		return nil
	}
	out := new(PxfServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PxfSpec) DeepCopyInto(out *PxfSpec) {
	*out = *in
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = new(PxfExtensionsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]PxfServerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomConnectors != nil {
		in, out := &in.CustomConnectors, &out.CustomConnectors
		*out = make([]PxfCustomConnector, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PxfSpec.
func (in *PxfSpec) DeepCopy() *PxfSpec {
	if in == nil {
		return nil
	}
	out := new(PxfSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryMonitoringExportersSpec) DeepCopyInto(out *QueryMonitoringExportersSpec) {
	*out = *in
	if in.PostgresExporter != nil {
		in, out := &in.PostgresExporter, &out.PostgresExporter
		*out = new(ExporterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeExporter != nil {
		in, out := &in.NodeExporter, &out.NodeExporter
		*out = new(ExporterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudberryQueryExporter != nil {
		in, out := &in.CloudberryQueryExporter, &out.CloudberryQueryExporter
		*out = new(ExporterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(QueryServiceMonitorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PrometheusRule != nil {
		in, out := &in.PrometheusRule, &out.PrometheusRule
		*out = new(QueryPrometheusRuleSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryMonitoringExportersSpec.
func (in *QueryMonitoringExportersSpec) DeepCopy() *QueryMonitoringExportersSpec {
	if in == nil {
		return nil
	}
	out := new(QueryMonitoringExportersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryMonitoringSpec) DeepCopyInto(out *QueryMonitoringSpec) {
	*out = *in
	if in.Exporters != nil {
		in, out := &in.Exporters, &out.Exporters
		*out = new(QueryMonitoringExportersSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryMonitoringSpec.
func (in *QueryMonitoringSpec) DeepCopy() *QueryMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(QueryMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryPrometheusRuleSpec) DeepCopyInto(out *QueryPrometheusRuleSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryPrometheusRuleSpec.
func (in *QueryPrometheusRuleSpec) DeepCopy() *QueryPrometheusRuleSpec {
	if in == nil {
		return nil
	}
	out := new(QueryPrometheusRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryServiceMonitorSpec) DeepCopyInto(out *QueryServiceMonitorSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryServiceMonitorSpec.
func (in *QueryServiceMonitorSpec) DeepCopy() *QueryServiceMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(QueryServiceMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebalanceSpec) DeepCopyInto(out *RebalanceSpec) {
	*out = *in
	if in.ExcludeTables != nil {
		in, out := &in.ExcludeTables, &out.ExcludeTables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebalanceSpec.
func (in *RebalanceSpec) DeepCopy() *RebalanceSpec {
	if in == nil {
		return nil
	}
	out := new(RebalanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationScanSpec) DeepCopyInto(out *RecommendationScanSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationScanSpec.
func (in *RecommendationScanSpec) DeepCopy() *RecommendationScanSpec {
	if in == nil {
		return nil
	}
	out := new(RecommendationScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceGroupSpec) DeepCopyInto(out *ResourceGroupSpec) {
	*out = *in
	if in.IOLimits != nil {
		in, out := &in.IOLimits, &out.IOLimits
		*out = make([]TablespaceIOLimitSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceGroupSpec.
func (in *ResourceGroupSpec) DeepCopy() *ResourceGroupSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceList) DeepCopyInto(out *ResourceList) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceList.
func (in *ResourceList) DeepCopy() *ResourceList {
	if in == nil {
		return nil
	}
	out := new(ResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(ResourceList)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ResourceList)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3CredentialSecret) DeepCopyInto(out *S3CredentialSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3CredentialSecret.
func (in *S3CredentialSecret) DeepCopy() *S3CredentialSecret {
	if in == nil {
		return nil
	}
	out := new(S3CredentialSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Destination) DeepCopyInto(out *S3Destination) {
	*out = *in
	if in.CredentialSecret != nil {
		in, out := &in.CredentialSecret, &out.CredentialSecret
		*out = new(S3CredentialSecret)
		**out = **in
	}
	if in.VaultSecret != nil {
		in, out := &in.VaultSecret, &out.VaultSecret
		*out = new(S3VaultSecret)
		**out = **in
	}
	if in.Multipart != nil {
		in, out := &in.Multipart, &out.Multipart
		*out = new(S3Multipart)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Destination.
func (in *S3Destination) DeepCopy() *S3Destination {
	if in == nil {
		return nil
	}
	out := new(S3Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Multipart) DeepCopyInto(out *S3Multipart) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Multipart.
func (in *S3Multipart) DeepCopy() *S3Multipart {
	if in == nil {
		return nil
	}
	out := new(S3Multipart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3VaultSecret) DeepCopyInto(out *S3VaultSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3VaultSecret.
func (in *S3VaultSecret) DeepCopy() *S3VaultSecret {
	if in == nil {
		return nil
	}
	out := new(S3VaultSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLSpec) DeepCopyInto(out *SSLSpec) {
	*out = *in
	if in.CertSecret != nil {
		in, out := &in.CertSecret, &out.CertSecret
		*out = new(CertSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLSpec.
func (in *SSLSpec) DeepCopy() *SSLSpec {
	if in == nil {
		return nil
	}
	out := new(SSLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SegmentsSpec) DeepCopyInto(out *SegmentsSpec) {
	*out = *in
	if in.Mirroring != nil {
		in, out := &in.Mirroring, &out.Mirroring
		*out = new(MirroringSpec)
		**out = **in
	}
	if in.Rebalance != nil {
		in, out := &in.Rebalance, &out.Rebalance
		*out = new(RebalanceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	out.Storage = in.Storage
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SegmentsSpec.
func (in *SegmentsSpec) DeepCopy() *SegmentsSpec {
	if in == nil {
		return nil
	}
	out := new(SegmentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandbySpec) DeepCopyInto(out *StandbySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandbySpec.
func (in *StandbySpec) DeepCopy() *StandbySpec {
	if in == nil {
		return nil
	}
	out := new(StandbySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageManagementSpec) DeepCopyInto(out *StorageManagementSpec) {
	*out = *in
	if in.RecommendationScan != nil {
		in, out := &in.RecommendationScan, &out.RecommendationScan
		*out = new(RecommendationScanSpec)
		**out = **in
	}
	if in.UsageReport != nil {
		in, out := &in.UsageReport, &out.UsageReport
		*out = new(UsageReportSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageManagementSpec.
func (in *StorageManagementSpec) DeepCopy() *StorageManagementSpec {
	if in == nil {
		return nil
	}
	out := new(StorageManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TablespaceIOLimitSpec) DeepCopyInto(out *TablespaceIOLimitSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TablespaceIOLimitSpec.
func (in *TablespaceIOLimitSpec) DeepCopy() *TablespaceIOLimitSpec {
	if in == nil {
		return nil
	}
	out := new(TablespaceIOLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Toleration) DeepCopyInto(out *Toleration) {
	*out = *in
	if in.TolerationSeconds != nil {
		in, out := &in.TolerationSeconds, &out.TolerationSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Toleration.
func (in *Toleration) DeepCopy() *Toleration {
	if in == nil {
		return nil
	}
	out := new(Toleration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageReportSpec) DeepCopyInto(out *UsageReportSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageReportSpec.
func (in *UsageReportSpec) DeepCopy() *UsageReportSpec {
	if in == nil {
		return nil
	}
	out := new(UsageReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSpec) DeepCopyInto(out *VaultSpec) {
	*out = *in
	if in.TLSSecret != nil {
		in, out := &in.TLSSecret, &out.TLSSecret
		*out = new(VaultTLSSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSpec.
func (in *VaultSpec) DeepCopy() *VaultSpec {
	if in == nil {
		return nil
	}
	out := new(VaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTLSSecret) DeepCopyInto(out *VaultTLSSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTLSSecret.
func (in *VaultTLSSecret) DeepCopy() *VaultTLSSecret {
	if in == nil {
		return nil
	}
	out := new(VaultTLSSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRule) DeepCopyInto(out *WorkloadRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRule.
func (in *WorkloadRule) DeepCopy() *WorkloadRule {
	if in == nil {
		return nil
	}
	out := new(WorkloadRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	if in.ResourceGroups != nil {
		in, out := &in.ResourceGroups, &out.ResourceGroups
		*out = make([]ResourceGroupSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]WorkloadRule, len(*in))
		copy(*out, *in)
	}
	if in.IdleRules != nil {
		in, out := &in.IdleRules, &out.IdleRules
		*out = make([]IdleSessionRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSpec.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}
