{{- if and .Values.oidc.enabled (not .Values.oidc.existingSecret) .Values.oidc.clientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudberry-operator.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudberry-operator.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.oidc.clientSecret | b64enc | quote }}
{{- end }}
