apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudberry-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudberry-operator.labels" . | nindent 4 }}
  {{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.port | quote }}
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  type: ClusterIP
  ports:
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    - name: health
      port: 8081
      targetPort: health
      protocol: TCP
  selector:
    {{- include "cloudberry-operator.selectorLabels" . | nindent 4 }}
---
{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudberry-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudberry-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: {{ .Values.webhook.port }}
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "cloudberry-operator.selectorLabels" . | nindent 4 }}
{{- end }}
